image: node:9-alpine

pages:
  script:
  - npm install
  - npm run build
  - mkdir public
  - cp -r index.html src/assets/img/opengraph.png dist public/
  artifacts:
    paths:
    - public/
  only:
  - master
